services:
  - type: web
    name: gps-trackerx-2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: RENDER
        value: true
    healthCheckPath: /api/status
